### ISSUE TITLE
Feature: Middleware login_required

### ISSUE THREAD

**Issue by loozzi** [loozzi/agile-line#8]
- Tạo middleware tên `login_required` ở thư mục _middlewares_
- `SECRET_KEY` khai báo ở trong file .env 
- Lấy thông tin người dùng, gán vào `request.user` để tiện cho quá trình sử dụng sau này
- Sử dụng thư viện `jwt` để thực hiện xác thực người dùng: https://pypi.org/project/jwt/
- Tham khảo: https://www.loginradius.com/blog/engineering/guest-post/securing-flask-api-with-jwt/

**Comment by VuThanhDat14122004** [comment]
# dev#1:(16/3/2024)
- created login_required.py
- update requirements.txt

**Comment by loozzi** [comment]
Branch: feature/8
Author: Vu Thanh Dat
Description:
- create middleware `token_required`
